### PR TITLE
Migrating to Swift 4

### PR DESCRIPTION
**Pull request by darquro**
Related to #28

### CODE REVIEW

**Comment by yarodevuci** [comment]
When it's gonna be merged ?

**Comment by jonajgs** [comment]
merge this request please!!

**Comment by Kukiwon** [comment]
Please merge!

**Comment by mana2love** [comment]
Please merge!

**Comment by s2mr** [comment]
Please merge!

**Comment by kiwo12345** [comment]
Merge..

**Comment by fosini** [comment]
Please merge

**Comment by darquro** [comment]
Hi everyone.
I made a new library of Heart button (because this repository may not be maintained).
It is a simple animation like Instagram, and the installation to an application is very easy.
If you need it in your application, please try it!

https://github.com/darquro/heart-button
<image src="https://user-images.githubusercontent.com/19259885/39964357-ce86be48-56bd-11e8-8e8b-a44e283ac2b7.gif" width="320px">

**Comment by lm2343635** [comment]
Please merge

**Comment by nikans** [comment]
Hey, @xhamr

Please add contributors as maintainers and we'll take it from there...

**Review by janselv — APPROVED** [review]

**Pull request merged**
