### PR TITLE
Added the possibility to change state without animation

### PR DESCRIPTION
**Pull request by okipol88**

### CODE REVIEW

**Review by ahmadabudawod — APPROVED** [review]

**Review by ahmadabudawod — APPROVED** [review]

**Comment by nudaya** [comment]
Guys, could you please merge these changes to the repo?

**Comment by RJiryes** [comment]
Can you please merge this? Thanks!

**Comment by nazywamsiepawel** [comment]
Can this please be merged?

**Comment by uknowmeright** [comment]
Please merge this? thank you

**Comment by nudaya** [comment]
+1
Please merge this. I have removed FaveButton due to non-availablility of this feature.

**Comment by eclair4151** [comment]
+1
Please merge this. Completely unusable if put in a cell in a list

for now you can do this if you don't mind pulling directly off this branch

in your pod file
pod 'FaveButton', :git => 'https://github.com/okipol88/fave-button', :branch => 'feature/selectionWithoutAnimation'


then in your code 
myButton.setSelected(selected: true, animated: false)

**Comment by bopeola21** [comment]
Please merge.

**Comment by n-cong** [comment]
merge, please!!!

**Review by janselv — APPROVED** [review]

**Pull request merged**
